### ISSUE TITLE
Allow type assertions for subclasses

### ISSUE THREAD

**Issue by ghost** [solid-software/solid_lints#123]
![image](https://github.com/solid-software/solid_lints/assets/145997968/d5df19c0-94d2-4a8d-a9fa-9915527172e7)

In the given example, `SubscriptionUpdate` class extends `SubscriptionEvent` so assertion should be necessary to define event's type

**Comment by yurii-prykhodko-solid** [comment]
Fixed here: https://github.com/solid-software/solid_lints/commit/8ed3f80931c0bb0778cbcb33956018bce13e1fe2
