### ISSUE TITLE
avoid-late - customization

### ISSUE THREAD

**Issue by illia-romanenko** [solid-software/solid_lints#63]
We want to allow cases:

- when late variable is initialized right away (allow-initialized=true)
- ignored-types related to animations aka AnimationController and any other relevant

**Comment by yurii-prykhodko-solid** [comment]
Already implemented: https://github.com/solid-software/solid_lints/blob/master/lib/src/lints/avoid_late_keyword/models/avoid_late_keyword_parameters.dart
