### ISSUE TITLE
Fix no_magic_number missing reports

### ISSUE THREAD

**Issue by vladimir-beloded** [solid-software/solid_lints#70]
The following test is failing, but shouldn't:
<img width="539" alt="image" src="https://github.com/solid-software/solid_lints/assets/98315622/6331be10-78cb-4020-9021-2466d0bd0305">

Also, it is needed to understand if we may have any similar situations or any situations we want to exclude.

**Comment by yurii-prykhodko-solid** [comment]
The concrete failing case fixed by #137
